export enum ActionTypesEnum {
    FETCH_ARTICLES_REQUEST = "FETCH_ARTICLES_REQUEST",
    FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS",
    FETCH_ARTICLES_FAIL = "FETCH_ARTICLES_FAIL",
    FETCH_ARTICLE_ID = "FETCH_ARTICLE_ID",
    ADMIN_LOGGED_IN = "ADMIN_LOGGED_IN",
    ADMIN_LOGOUT = "ADMIN_LOGOUT",
    DELETE_ARTICLES_SUCCESS = "DELETE_ARTICLES_SUCCESS",
    FETCH_ARTICLE_ID_SUCCESS = "FETCH_ARTICLE_ID_SUCCESS",
    NEW_COMMENT_CNT = "NEW_COMMENT_CNT",
    NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL",
    ADD_COMMENT = "ADD_COMMENT"
}